---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          env:
            DB_HOST: db
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_NAME: devdb
          run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        - name: Lint
          run: docker compose run --rm app sh -c "flake8"
